from connection import connectToMongoDB, closeConnection
from bson import ObjectId, Decimal128
from datetime import datetime
import random

mongoClient, db = connectToMongoDB()

productsCollection = db['products']

vendors = [
    {"companyName": "Innovatech Solutions", "contactEmail": "sales@innovatech.com", "supportPhone": "+1-888-123-4567"},
    {"companyName": "Apex Gadgetry", "contactEmail": "support@apexgadgetry.com", "supportPhone": "+1-888-234-5678"},
    {"companyName": "Quantum Devices", "contactEmail": "info@quantumdev.com", "supportPhone": "+1-888-345-6789"},
    {"companyName": "Stellar Goods", "contactEmail": "contact@stellargoods.net", "supportPhone": "+1-888-456-7890"},
    {"companyName": "Fusion Homewares", "contactEmail": "support@fusionhome.com", "supportPhone": "+1-888-567-8901"},
    {"companyName": "Ember Kitchen", "contactEmail": "sales@emberkitchen.io", "supportPhone": "+1-888-678-9012"},
    {"companyName": "Velocity Sports Gear", "contactEmail": "info@velocitysports.com", "supportPhone": "+1-888-789-0123"},
    {"companyName": "Zenith Athletics", "contactEmail": "contact@zenithathletics.com", "supportPhone": "+1-888-890-1234"},
    {"companyName": "Bibliophile's Corner", "contactEmail": "orders@bibliophilescorner.com", "supportPhone": "+1-888-901-2345"},
    {"companyName": "The Story Weaver", "contactEmail": "support@storyweaver.pub", "supportPhone": "+1-888-012-3456"},
    {"companyName": "Chic Threads Apparel", "contactEmail": "sales@chicthreads.com", "supportPhone": "+1-888-112-2334"},
    {"companyName": "Urban Vogue Outfitters", "contactEmail": "info@urbanvogue.com", "supportPhone": "+1-888-223-3445"},
    {"companyName": "Digital Horizon", "contactEmail": "contact@digitalhorizon.tech", "supportPhone": "+1-888-334-4556"},
    {"companyName": "Pinnacle Performance", "contactEmail": "info@pinnacleperf.com", "supportPhone": "+1-888-445-5667"},
    {"companyName": "Evergreen Books", "contactEmail": "support@evergreenbooks.com", "supportPhone": "+1-888-556-6778"},
    {"companyName": "StyleSphere", "contactEmail": "contact@stylesphere.co", "supportPhone": "+1-888-667-7889"},
    {"companyName": "Gourmet Gadgets", "contactEmail": "sales@gourmetgadgets.com", "supportPhone": "+1-888-778-8990"},
    {"companyName": "Celestial Tech", "contactEmail": "support@celestial.tech", "supportPhone": "+1-888-111-2222"},
    {"companyName": "TerraFirm Gear", "contactEmail": "info@terrafirm.gear", "supportPhone": "+1-888-333-4444"},
    {"companyName": "AquaLuxe Kitchenware", "contactEmail": "sales@aqualuxe.kitchen", "supportPhone": "+1-888-555-6666"},
    {"companyName": "Momentum Active", "contactEmail": "contact@momentumactive.com", "supportPhone": "+1-888-777-8888"},
    {"companyName": "The Scholar's Press", "contactEmail": "publishing@scholarspress.com", "supportPhone": "+1-888-999-0000"},
    {"companyName": "Atelier Apparel", "contactEmail": "cs@atelierapparel.com", "supportPhone": "+1-888-212-3232"},
    {"companyName": "Zenith Sports Dynamics", "contactEmail": "relations@zenithdynamics.sport", "supportPhone": "+1-888-434-5454"},
    {"companyName": "The Culinary Edge", "contactEmail": "help@culinaryedge.co", "supportPhone": "+1-888-656-7676"},
    {"companyName": "Nexus Innovations", "contactEmail": "contact@nexusinnov.com", "supportPhone": "+1-888-121-2121"},
    {"companyName": "Horizon Dynamics", "contactEmail": "support@horizondynamics.com", "supportPhone": "+1-888-343-4343"},
    {"companyName": "Aurora Tech", "contactEmail": "info@auroratech.io", "supportPhone": "+1-888-565-6565"},
    {"companyName": "Silverline Goods", "contactEmail": "sales@silverlinegoods.com", "supportPhone": "+1-888-787-8787"},
    {"companyName": "Phoenix United", "contactEmail": "contact@phoenixunited.com", "supportPhone": "+1-888-909-0909"},
    {"companyName": "Summit Supply Co.", "contactEmail": "support@summitsupply.co", "supportPhone": "+1-888-112-3456"},
    {"companyName": "Keystone Merchants", "contactEmail": "info@keystonemerchants.com", "supportPhone": "+1-888-223-4567"},
    {"companyName": "Redwood & Oak", "contactEmail": "sales@redwoodandoak.com", "supportPhone": "+1-888-334-5678"},
    {"companyName": "Northstar Provisions", "contactEmail": "contact@northstarprovisions.com", "supportPhone": "+1-888-445-6789"},
    {"companyName": "Tidal Wave Inc.", "contactEmail": "support@tidalwaveinc.com", "supportPhone": "+1-888-556-7890"},
    {"companyName": "Ironclad Systems", "contactEmail": "info@ironcladsys.com", "supportPhone": "+1-888-667-8901"},
    {"companyName": "Crimson Arrow", "contactEmail": "sales@crimsonarrow.com", "supportPhone": "+1-888-778-9012"},
    {"companyName": "Blue Jay Books", "contactEmail": "orders@bluejaybooks.com", "supportPhone": "+1-888-889-0123"},
    {"companyName": "Golden Grain Foods", "contactEmail": "support@goldengrain.com", "supportPhone": "+1-888-990-1234"},
    {"companyName": "Emerald City Goods", "contactEmail": "contact@emeraldcitygoods.com", "supportPhone": "+1-888-001-2345"},
    {"companyName": "Black Diamond Gear", "contactEmail": "info@blackdiamondgear.com", "supportPhone": "+1-888-111-3456"},
    {"companyName": "White Wolf Wares", "contactEmail": "sales@whitewolfwares.com", "supportPhone": "+1-888-222-4567"},
    {"companyName": "Purple Finch Publishing", "contactEmail": "contact@purplefinch.pub", "supportPhone": "+1-888-333-5678"},
    {"companyName": "Gray Fox Tech", "contactEmail": "support@grayfoxtech.com", "supportPhone": "+1-888-444-6789"},
    {"companyName": "Green Turtle Gaming", "contactEmail": "info@greenturtlegaming.com", "supportPhone": "+1-888-555-7890"},
    {"companyName": "Brown Bear Bistro", "contactEmail": "contact@brownbearbistro.com", "supportPhone": "+1-888-666-8901"},
    {"companyName": "Orange Octopus Optics", "contactEmail": "sales@orangeoctopus.com", "supportPhone": "+1-888-777-9012"},
    {"companyName": "Yellow Jacket Sports", "contactEmail": "info@yellowjacketsports.com", "supportPhone": "+1-888-888-0123"},
    {"companyName": "Violet Vixen Vogue", "contactEmail": "support@violetvixenvogue.com", "supportPhone": "+1-888-999-1234"},
    {"companyName": "Ivory Elephant Imports", "contactEmail": "contact@ivoryelephant.com", "supportPhone": "+1-888-101-2345"},
    {"companyName": "Scarlet Sparrow Styles", "contactEmail": "sales@scarletsparrow.com", "supportPhone": "+1-888-212-3456"},
    {"companyName": "Azure Turtle Toys", "contactEmail": "info@azureturtle.com", "supportPhone": "+1-888-323-4567"},
    {"companyName": "Cerulean Swan Solutions", "contactEmail": "support@ceruleanswan.com", "supportPhone": "+1-888-434-5678"},
    {"companyName": "Saffron Stallion Sports", "contactEmail": "contact@saffronstallion.com", "supportPhone": "+1-888-545-6789"},
    {"companyName": "Veridian Valley Ventures", "contactEmail": "info@veridianvalley.com", "supportPhone": "+1-888-656-7890"},
    {"companyName": "Magenta Moose Media", "contactEmail": "sales@magentamoose.com", "supportPhone": "+1-888-767-8901"},
    {"companyName": "Teal Tiger Tech", "contactEmail": "contact@tealtiger.tech", "supportPhone": "+1-888-878-9012"},
    {"companyName": "Lavender Lion Linens", "contactEmail": "support@lavenderlion.com", "supportPhone": "+1-888-989-0123"},
    {"companyName": "Crimson Cobra Creations", "contactEmail": "info@crimsoncobra.com", "supportPhone": "+1-888-090-1234"},
    {"companyName": "Onyx Otter Outfitters", "contactEmail": "sales@onyxotter.com", "supportPhone": "+1-888-101-1234"},
    {"companyName": "Jade Jaguar Jewelers", "contactEmail": "contact@jadejaguar.com", "supportPhone": "+1-888-212-2345"},
    {"companyName": "Topaz Toucan Travel", "contactEmail": "support@topaztoucan.com", "supportPhone": "+1-888-323-3456"},
    {"companyName": "Ruby Rooster Restaurant", "contactEmail": "info@rubyrooster.com", "supportPhone": "+1-888-434-4567"},
    {"companyName": "Sapphire Shark Supplies", "contactEmail": "sales@sapphireshark.com", "supportPhone": "+1-888-545-5678"},
    {"companyName": "Garnet Griffin Gear", "contactEmail": "contact@garnetgriffin.com", "supportPhone": "+1-888-656-6789"},
    {"companyName": "Amethyst Antelope Apparel", "contactEmail": "support@amethystantelope.com", "supportPhone": "+1-888-767-7890"},
    {"companyName": "Aquamarine Alligator Art", "contactEmail": "info@aquamarinealligator.com", "supportPhone": "+1-888-878-8901"},
    {"companyName": "Diamond Dolphin Designs", "contactEmail": "sales@diamonddolphin.com", "supportPhone": "+1-888-989-9012"},
    {"companyName": "Pearl Peacock Products", "contactEmail": "contact@pearlpeacock.com", "supportPhone": "+1-888-090-0123"},
    {"companyName": "Peridot Panther Publishing", "contactEmail": "support@peridotpanther.com", "supportPhone": "+1-888-101-1122"},
    {"companyName": "Spinel Sparrow Sports", "contactEmail": "info@spinelsparrow.com", "supportPhone": "+1-888-212-2233"},
    {"companyName": "Tourmaline Tiger Toys", "contactEmail": "sales@tourmalinetiger.com", "supportPhone": "+1-888-323-3344"},
    {"companyName": "Zircon Zebra Zenith", "contactEmail": "contact@zirconzebra.com", "supportPhone": "+1-888-434-4455"},
    {"companyName": "Amber Ape Adventures", "contactEmail": "support@amberape.com", "supportPhone": "+1-888-545-5566"}
]

userNames = [
    "James Smith", "John Johnson", "Robert Williams", "Michael Brown", "William Jones", "David Garcia", "Richard Miller", "Joseph Davis", "Thomas Rodriguez", "Charles Martinez",
    "Christopher Hernandez", "Daniel Lopez", "Matthew Gonzales", "Anthony Wilson", "Mark Anderson", "Donald Thomas", "Steven Taylor", "Paul Moore", "Andrew Jackson", "Joshua Martin",
    "Kenneth Lee", "Kevin Perez", "Brian Thompson", "George White", "Edward Harris", "Ronald Sanchez", "Timothy Clark", "Jason Ramirez", "Jeffrey Lewis", "Ryan Robinson",
    "Jacob Walker", "Gary Young", "Nicholas Allen", "Eric King", "Jonathan Wright", "Stephen Scott", "Larry Torres", "Justin Nguyen", "Scott Hill", "Brandon Flores",
    "Benjamin Green", "Samuel Adams", "Gregory Nelson", "Frank Baker", "Alexander Hall", "Raymond Campbell", "Patrick Mitchell", "Jack Carter", "Dennis Roberts", "Jerry Gomez",
    "Tyler Phillips", "Aaron Evans", "Jose Turner", "Adam Diaz", "Henry Parker", "Nathan Cruz", "Douglas Edwards", "Zachary Collins", "Peter Reyes", "Kyle Stewart",
    "Walter Morris", "Ethan Morales", "Jeremy Murphy", "Harold Cook", "Keith Rogers", "Christian Gutierrez", "Roger Ortiz", "Noah Morgan", "Gerald Cooper", "Carl Peterson",
    "Terry Bailey", "Sean Reed", "Arthur Kelly", "Austin Howard", "Noah Ramos", "Lawrence Kim", "Jesse Cox", "Joe Ward", "Bryan Richardson", "Billy Watson",
    "Jordan Brooks", "Albert Chavez", "Dylan Wood", "Bruce James", "Willie Bennett", "Gabriel Gray", "Alan Mendoza", "Juan Ruiz", "Logan Hughes", "Wayne Price",
    "Ralph Alvarez", "Roy Castillo", "Eugene Sanders", "Randy Patel", "Vincent Myers", "Russell Long", "Elijah Ross", "Louis Foster", "Bobby Jimenez", "Philip Smith",
    "Johnny Johnson", "Mary Williams", "Patricia Brown", "Jennifer Jones", "Linda Garcia", "Elizabeth Miller", "Barbara Davis", "Susan Rodriguez", "Jessica Martinez", "Sarah Hernandez",
    "Karen Lopez", "Nancy Gonzales", "Lisa Wilson", "Betty Anderson", "Margaret Thomas", "Sandra Taylor", "Ashley Moore", "Kimberly Jackson", "Emily Martin", "Donna Lee",
    "Michelle Perez", "Dorothy Thompson", "Carol White", "Amanda Harris", "Melissa Sanchez", "Deborah Clark", "Stephanie Ramirez", "Rebecca Lewis", "Sharon Robinson", "Laura Walker",
    "Cynthia Young", "Kathleen Allen", "Amy King", "Shirley Wright", "Angela Scott", "Helen Torres", "Anna Nguyen", "Brenda Hill", "Pamela Flores", "Nicole Green",
    "Emma Adams", "Samantha Nelson", "Katherine Baker", "Christine Hall", "Debra Campbell", "Rachel Mitchell", "Catherine Carter", "Carolyn Roberts", "Janet Gomez", "Ruth Phillips",
    "Maria Evans", "Heather Turner", "Diane Diaz", "Virginia Parker", "Julie Cruz", "Joyce Edwards", "Victoria Collins", "Olivia Reyes", "Kelly Stewart", "Christina Morris",
    "Lauren Morales", "Joan Murphy", "Evelyn Cook", "Judith Rogers", "Megan Gutierrez", "Cheryl Ortiz", "Andrea Morgan", "Hannah Cooper", "Martha Peterson", "Jacqueline Bailey",
    "Frances Reed", "Gloria Kelly", "Ann Howard", "Teresa Ramos", "Kathryn Kim", "Sara Cox", "Janice Ward", "Jean Richardson", "Alice Watson", "Madison Brooks",
    "Doris Chavez", "Rose Wood", "Julie James", "Judy Bennett", "Grace Gray", "Denise Mendoza", "Beverly Ruiz", "Marilyn Hughes", "Amber Price", "Danielle Alvarez",
    "Brittany Castillo", "Diana Sanders", "Jane Patel", "Lori Myers", "Olivia Long", "Tiffany Ross", "Kathy Foster", "Tammy Jimenez", "Crystal Smith", "Tina Johnson", "Sophia Williams",
    "James Brown", "John Jones", "Robert Garcia", "Michael Miller", "William Davis", "David Rodriguez", "Richard Martinez", "Joseph Hernandez", "Thomas Lopez", "Charles Gonzales",
    "Christopher Wilson", "Daniel Anderson", "Matthew Thomas", "Anthony Taylor", "Mark Moore", "Donald Jackson", "Steven Martin", "Paul Lee", "Andrew Perez", "Joshua Thompson",
    "Kenneth White", "Kevin Harris", "Brian Sanchez", "George Clark", "Edward Ramirez", "Ronald Lewis", "Timothy Robinson", "Jason Walker", "Jeffrey Young", "Ryan Allen",
    "Jacob King", "Gary Wright", "Nicholas Scott", "Eric Torres", "Jonathan Nguyen", "Stephen Hill", "Larry Flores", "Justin Green", "Scott Adams", "Brandon Nelson",
    "Benjamin Baker", "Samuel Hall", "Gregory Campbell", "Frank Mitchell", "Alexander Carter", "Raymond Roberts", "Patrick Gomez", "Jack Phillips", "Dennis Evans", "Jerry Turner",
    "Tyler Diaz", "Aaron Parker", "Jose Cruz", "Adam Edwards", "Henry Collins", "Nathan Reyes", "Douglas Stewart", "Zachary Morris", "Peter Morales", "Kyle Murphy",
    "Walter Cook", "Ethan Rogers", "Jeremy Gutierrez", "Harold Ortiz", "Keith Morgan", "Christian Cooper", "Roger Peterson", "Noah Bailey", "Gerald Reed", "Carl Kelly",
    "Terry Howard", "Sean Ramos", "Arthur Kim", "Austin Cox", "Noah Ward", "Lawrence Richardson", "Jesse Watson", "Joe Brooks", "Bryan Chavez", "Billy Wood",
    "Jordan James", "Albert Bennett", "Dylan Gray", "Bruce Mendoza", "Willie Ruiz", "Gabriel Hughes", "Alan Price", "Juan Alvarez", "Logan Castillo", "Wayne Sanders",
    "Ralph Patel", "Roy Myers", "Eugene Long", "Randy Ross", "Vincent Foster", "Russell Jimenez", "Elijah Smith", "Louis Johnson", "Bobby Williams", "Philip Brown", "Johnny Jones",
    "Mary Garcia", "Patricia Miller", "Jennifer Davis", "Linda Rodriguez", "Elizabeth Martinez", "Barbara Hernandez", "Susan Lopez", "Jessica Gonzales", "Sarah Wilson", "Karen Anderson",
    "Nancy Thomas", "Lisa Taylor", "Betty Moore", "Margaret Jackson", "Sandra Martin", "Ashley Lee", "Kimberly Perez", "Emily Thompson", "Donna White", "Michelle Harris",
    "Dorothy Sanchez", "Carol Clark", "Amanda Ramirez", "Melissa Lewis", "Deborah Robinson", "Stephanie Walker", "Rebecca Young", "Sharon Allen", "Laura King", "Cynthia Wright",
    "Kathleen Scott", "Amy Torres", "Shirley Nguyen", "Angela Hill", "Helen Flores", "Anna Green", "Brenda Adams", "Pamela Nelson", "Nicole Baker", "Emma Hall",
    "Samantha Campbell", "Katherine Mitchell", "Christine Carter", "Debra Roberts", "Rachel Gomez", "Catherine Phillips", "Carolyn Evans", "Janet Turner", "Ruth Diaz", "Maria Parker",
    "Heather Cruz", "Diane Edwards", "Virginia Collins", "Julie Reyes", "Joyce Stewart", "Victoria Morris", "Olivia Morales", "Kelly Murphy", "Christina Cook", "Lauren Rogers",
    "Joan Gutierrez", "Evelyn Ortiz", "Judith Morgan", "Megan Cooper", "Cheryl Peterson", "Andrea Bailey", "Hannah Reed", "Martha Kelly", "Jacqueline Howard", "Frances Ramos",
    "Gloria Kim", "Ann Cox", "Teresa Ward", "Kathryn Richardson", "Sara Watson", "Janice Brooks", "Jean Chavez", "Alice Wood", "Madison James", "Doris Bennett",
    "Rose Gray", "Julie Mendoza", "Judy Ruiz", "Grace Hughes", "Denise Price", "Beverly Alvarez", "Marilyn Castillo", "Amber Sanders", "Danielle Patel", "Brittany Myers",
    "Diana Long", "Jane Ross", "Lori Foster", "Olivia Jimenez", "Tiffany Smith", "Kathy Johnson", "Tammy Williams", "Crystal Brown", "Tina Jones", "Sophia Garcia",
    "James Miller", "John Davis", "Robert Rodriguez", "Michael Martinez", "William Hernandez", "David Lopez", "Richard Gonzales", "Joseph Wilson", "Thomas Anderson", "Charles Thomas",
    "Christopher Taylor", "Daniel Moore", "Matthew Jackson", "Anthony Martin", "Mark Lee", "Donald Perez", "Steven Thompson", "Paul White", "Andrew Harris", "Joshua Sanchez",
    "Kenneth Clark", "Kevin Ramirez", "Brian Lewis", "George Robinson", "Edward Walker", "Ronald Young", "Timothy Allen", "Jason King", "Jeffrey Wright", "Ryan Scott",
    "Jacob Torres", "Gary Nguyen", "Nicholas Hill", "Eric Flores", "Jonathan Green", "Stephen Adams", "Larry Nelson", "Justin Baker", "Scott Hall", "Brandon Campbell",
    "Benjamin Mitchell", "Samuel Carter", "Gregory Roberts", "Frank Gomez", "Alexander Phillips", "Raymond Evans", "Patrick Turner", "Jack Diaz", "Dennis Parker", "Jerry Cruz",
    "Tyler Edwards", "Aaron Collins", "Jose Reyes", "Adam Stewart", "Henry Morris", "Nathan Morales", "Douglas Murphy", "Zachary Cook", "Peter Rogers", "Kyle Gutierrez",
    "Walter Ortiz", "Ethan Morgan", "Jeremy Cooper", "Harold Peterson", "Keith Bailey", "Christian Reed", "Roger Kelly", "Noah Howard", "Gerald Ramos", "Carl Kim",
    "Terry Cox", "Sean Ward", "Arthur Richardson", "Austin Watson", "Noah Brooks", "Lawrence Chavez", "Jesse Wood", "Joe James", "Bryan Bennett", "Billy Gray",
    "Jordan Mendoza", "Albert Ruiz", "Dylan Hughes", "Bruce Price", "Willie Alvarez", "Gabriel Castillo", "Alan Sanders", "Juan Patel", "Logan Myers", "Wayne Long",
    "Ralph Ross", "Roy Foster", "Eugene Jimenez", "Randy Smith", "Vincent Johnson", "Russell Williams", "Elijah Brown", "Louis Jones", "Bobby Garcia", "Philip Miller", "Johnny Davis",
    "Mary Rodriguez", "Patricia Martinez", "Jennifer Hernandez", "Linda Lopez", "Elizabeth Gonzales", "Barbara Wilson", "Susan Anderson", "Jessica Thomas", "Sarah Taylor", "Karen Moore",
    "Nancy Jackson", "Lisa Martin", "Betty Lee", "Margaret Perez", "Sandra Thompson", "Ashley White", "Kimberly Harris", "Emily Sanchez", "Donna Clark", "Michelle Ramirez",
    "Dorothy Lewis", "Carol Robinson", "Amanda Walker", "Melissa Young", "Deborah Allen", "Stephanie King", "Rebecca Wright", "Sharon Scott", "Laura Torres", "Cynthia Nguyen",
    "Kathleen Hill", "Amy Flores", "Shirley Green", "Angela Adams", "Helen Nelson", "Anna Baker", "Brenda Hall", "Pamela Campbell", "Nicole Mitchell", "Emma Carter",
    "Samantha Roberts", "Katherine Gomez", "Christine Phillips", "Debra Evans", "Rachel Turner", "Catherine Diaz", "Carolyn Parker", "Janet Cruz", "Ruth Edwards", "Maria Collins",
    "Heather Reyes", "Diane Stewart", "Virginia Morris", "Julie Morales", "Joyce Murphy", "Victoria Cook", "Olivia Rogers", "Kelly Gutierrez", "Christina Ortiz", "Lauren Morgan",
    "Joan Cooper", "Evelyn Peterson", "Judith Bailey", "Megan Reed", "Cheryl Kelly", "Andrea Howard", "Hannah Ramos", "Martha Kim", "Jacqueline Cox", "Frances Ward",
    "Gloria Richardson", "Ann Watson", "Teresa Brooks", "Kathryn Chavez", "Sara Wood", "Janice James", "Jean Bennett", "Alice Gray", "Madison Mendoza", "Doris Ruiz",
    "Rose Hughes", "Julie Price", "Judy Alvarez", "Grace Castillo", "Denise Sanders", "Beverly Patel", "Marilyn Myers", "Amber Long", "Danielle Ross", "Brittany Foster",
    "Diana Jimenez", "Jane Smith", "Lori Johnson", "Olivia Williams", "Tiffany Brown", "Kathy Jones", "Tammy Garcia", "Crystal Miller", "Tina Davis", "Sophia Rodriguez",
    "James Martinez", "John Hernandez", "Robert Lopez", "Michael Gonzales", "William Wilson", "David Anderson", "Richard Thomas", "Joseph Taylor", "Thomas Moore", "Charles Jackson",
    "Christopher Martin", "Daniel Lee", "Matthew Perez", "Anthony Thompson", "Mark White", "Donald Harris", "Steven Sanchez", "Paul Clark", "Andrew Ramirez", "Joshua Lewis",
    "Kenneth Robinson", "Kevin Walker", "Brian Young", "George Allen", "Edward King", "Ronald Wright", "Timothy Scott", "Jason Torres", "Jeffrey Nguyen", "Ryan Hill",
    "Jacob Flores", "Gary Green", "Nicholas Adams", "Eric Nelson", "Jonathan Baker", "Stephen Hall", "Larry Campbell", "Justin Mitchell", "Scott Carter", "Brandon Roberts",
    "Benjamin Gomez", "Samuel Phillips", "Gregory Evans", "Frank Turner", "Alexander Diaz", "Raymond Parker", "Patrick Cruz", "Jack Edwards", "Dennis Collins", "Jerry Reyes",
    "Tyler Stewart", "Aaron Morris", "Jose Morales", "Adam Murphy", "Henry Cook", "Nathan Rogers", "Douglas Gutierrez", "Zachary Ortiz", "Peter Morgan", "Kyle Cooper",
    "Walter Peterson", "Ethan Bailey", "Jeremy Reed", "Harold Kelly", "Keith Howard", "Christian Ramos", "Roger Kim", "Noah Cox", "Gerald Ward", "Carl Richardson",
    "Terry Watson", "Sean Brooks", "Arthur Chavez", "Austin Wood", "Noah James", "Lawrence Bennett", "Jesse Gray", "Joe Mendoza", "Bryan Ruiz", "Billy Hughes",
    "Jordan Price", "Albert Alvarez", "Dylan Castillo", "Bruce Sanders", "Willie Patel", "Gabriel Myers", "Alan Long", "Juan Ross", "Logan Foster", "Wayne Jimenez",
    "Ralph Smith", "Roy Johnson", "Eugene Williams", "Randy Brown", "Vincent Jones", "Russell Garcia", "Elijah Miller", "Louis Davis", "Bobby Rodriguez", "Philip Martinez", "Johnny Hernandez",
    "Mary Lopez", "Patricia Gonzales", "Jennifer Wilson", "Linda Anderson", "Elizabeth Thomas", "Barbara Taylor", "Susan Moore", "Jessica Jackson", "Sarah Martin", "Karen Lee",
    "Nancy Perez", "Lisa Thompson", "Betty White", "Margaret Harris", "Sandra Sanchez", "Ashley Clark", "Kimberly Ramirez", "Emily Lewis", "Donna Robinson", "Michelle Walker",
    "Dorothy Young", "Carol Allen", "Amanda King", "Melissa Wright", "Deborah Scott", "Stephanie Torres", "Rebecca Nguyen", "Sharon Hill", "Laura Flores", "Cynthia Green",
    "Kathleen Adams", "Amy Nelson", "Shirley Baker", "Angela Hall", "Helen Campbell", "Anna Mitchell", "Brenda Carter", "Pamela Roberts", "Nicole Gomez", "Emma Phillips",
    "Samantha Evans", "Katherine Turner", "Christine Diaz", "Debra Parker", "Rachel Cruz", "Catherine Edwards", "Carolyn Collins", "Janet Reyes", "Ruth Stewart", "Maria Morris",
    "Heather Morales", "Diane Murphy", "Virginia Cook", "Julie Rogers", "Joyce Gutierrez", "Victoria Ortiz", "Olivia Morgan", "Kelly Cooper", "Christina Peterson", "Lauren Bailey",
    "Joan Reed", "Evelyn Kelly", "Judith Howard", "Megan Ramos", "Cheryl Kim", "Andrea Cox", "Hannah Ward", "Martha Richardson", "Jacqueline Watson", "Frances Brooks",
    "Gloria Chavez", "Ann Wood", "Teresa James", "Kathryn Bennett", "Sara Gray", "Janice Mendoza", "Jean Ruiz", "Alice Hughes", "Madison Price", "Doris Alvarez",
    "Rose Castillo", "Julie Sanders", "Judy Patel", "Grace Myers", "Denise Long", "Beverly Ross", "Marilyn Foster", "Amber Jimenez", "Danielle Smith", "Brittany Johnson",
    "Diana Williams", "Jane Brown", "Lori Jones", "Olivia Garcia", "Tiffany Miller", "Kathy Davis", "Tammy Rodriguez", "Crystal Martinez", "Tina Hernandez", "Sophia Lopez",
    "James Gonzales", "John Wilson", "Robert Anderson", "Michael Thomas", "William Taylor", "David Moore", "Richard Jackson", "Joseph Martin", "Thomas Lee", "Charles Perez",
    "Christopher Thompson", "Daniel White", "Matthew Harris", "Anthony Sanchez", "Mark Clark", "Donald Ramirez", "Steven Lewis", "Paul Robinson", "Andrew Walker", "Joshua Young",
    "Kenneth Allen", "Kevin King", "Brian Wright", "George Scott", "Edward Torres", "Ronald Nguyen", "Timothy Hill", "Jason Flores", "Jeffrey Green", "Ryan Adams",
    "Jacob Nelson", "Gary Baker", "Nicholas Hall", "Eric Campbell", "Jonathan Mitchell", "Stephen Carter", "Larry Roberts", "Justin Gomez", "Scott Phillips", "Brandon Evans",
    "Benjamin Turner", "Samuel Diaz", "Gregory Parker", "Frank Cruz", "Alexander Edwards", "Raymond Collins", "Patrick Reyes", "Jack Stewart", "Dennis Morris", "Jerry Morales",
    "Tyler Murphy", "Aaron Cook", "Jose Rogers", "Adam Gutierrez", "Henry Ortiz", "Nathan Morgan", "Douglas Cooper", "Zachary Peterson", "Peter Bailey", "Kyle Reed",
    "Walter Kelly", "Ethan Howard", "Jeremy Ramos", "Harold Kim", "Keith Cox", "Christian Ward", "Roger Richardson", "Noah Watson", "Gerald Brooks", "Carl Chavez",
    "Terry Wood", "Sean James", "Arthur Bennett", "Austin Gray", "Noah Mendoza", "Lawrence Ruiz", "Jesse Hughes", "Joe Price", "Bryan Alvarez", "Billy Castillo",
    "Jordan Sanders", "Albert Patel", "Dylan Myers", "Bruce Long", "Willie Ross", "Gabriel Foster", "Alan Jimenez", "Juan Smith", "Logan Johnson", "Wayne Williams",
    "Ralph Brown", "Roy Jones", "Eugene Garcia", "Randy Miller", "Vincent Davis", "Russell Rodriguez", "Elijah Martinez", "Louis Hernandez", "Bobby Lopez", "Philip Gonzales", "Johnny Wilson"
]


comments = [
    "Excellent product, highly recommended! A true game changer.",
    "Good value for money. Does exactly what it promises.",
    "Not as expected, a bit disappointed with the build quality.",
    "Amazing quality and lightning-fast shipping! Will buy again.",
    "Works perfectly, very satisfied with this purchase.",
    "Could be better for the price. The features are a bit lacking.",
    "Outstanding performance! It exceeded all my expectations.",
    "Decent product but feels overpriced for what it is.",
    "Best purchase I've made this year. Absolutely fantastic!",
    "Average quality, nothing special to write home about.",
    "Fantastic! I'm blown away by how good this is.",
    "Poor quality, returning it immediately. Avoid this product.",
    "Great features but the battery life is a major letdown.",
    "Love it! It has become an essential part of my daily routine.",
    "Not worth the money. You can find better alternatives.",
    "The design is sleek and modern. Looks great on my desk.",
    "Customer support was incredibly helpful with my issue.",
    "The instructions were confusing, took a while to set up.",
    "Five stars! Does the job flawlessly.",
    "I've been using this for a month now and it's still going strong.",
    "It broke after just a week of use. Very fragile.",
    "A solid product that delivers on its promises.",
    "The color is much nicer in person than in the pictures.",
    "Slightly smaller than I anticipated, but still works well.",
    "A must-have for anyone serious about quality.",
    "The packaging was damaged on arrival, but the product was fine.",
    "It's okay. Not great, not terrible. Just okay.",
    "I bought this as a gift and they absolutely loved it!",
    "The software is a bit buggy, hoping for an update soon.",
    "Incredible value. Feels much more expensive than it is.",
    "This is a revolutionary product. Can't imagine my life without it.",
    "The setup was a breeze, up and running in minutes.",
    "It's a bit noisy during operation, which is a downside.",
    "I had high hopes, but it didn't live up to the hype.",
    "Impressive battery life, lasts for days on a single charge.",
    "The user interface is intuitive and easy to navigate.",
    "Aesthetically pleasing, but the performance is just average.",
    "It feels very durable and well-made. Should last a long time.",
    "The warranty process was a nightmare. Terrible customer service.",
    "Perfect for my needs. Exactly what I was looking for.",
    "The app that comes with it is surprisingly polished and useful.",
    "It gets the job done, but I wish it had more features.",
    "There's a steep learning curve, but it's worth it in the end.",
    "This was an impulse buy, and I have zero regrets.",
    "The product arrived earlier than expected, which was a nice surprise.",
    "I'm on the fence about this one. It has its pros and cons.",
    "The build quality is top-notch. Feels very premium.",
    "It's a good entry-level option for beginners.",
    "I would recommend this to a friend without hesitation.",
    "The performance is inconsistent. Sometimes it's great, sometimes it's not.",
    "The materials used feel cheap and flimsy. I expected more.",
    "It's a bit bulky, but the performance makes up for it.",
    "The price is a bit high, but you get what you pay for.",
    "I've had this for over a year, and it's still working like new.",
    "The feature set is impressive for this price point.",
    "It's a decent product, but the competition offers more.",
    "The instructions were clear and easy to follow.",
    "I had to return the first one due to a defect, but the replacement works fine.",
    "This product has completely streamlined my workflow.",
    "It's a simple, no-frills product that does its job well.",
    "The product looks exactly like the photos online.",
    "I'm very impressed with the attention to detail.",
    "It's a bit of a gimmick, but a fun one at that.",
    "The product has a weird smell that won't go away.",
    "I wish I had bought this sooner. It's been a great help.",
    "The customer reviews were spot on. This is a great product.",
    "It's not compatible with my other devices, which is a shame.",
    "The product is very easy to clean and maintain.",
    "I'm giving it four stars because there's always room for improvement.",
    "The product is a bit heavy, making it less portable.",
    "I'm not sure I would buy this again, but it's been okay.",
    "The product is very versatile and can be used for many things.",
    "I'm a loyal customer of this brand, and they never disappoint.",
    "The product is a bit of a letdown. I expected more from this brand.",
    "I'm very happy with my purchase. It's been a great investment.",
    "The product is a bit flimsy. I'm worried it won't last long.",
    "I've recommended this to all my friends and family.",
    "The product is a bit of a novelty, but I enjoy using it.",
    "I'm very impressed with the quality of this product.",
    "The product is a bit of a disappointment. I wouldn't recommend it.",
    "I'm very satisfied with this product. It's been a great addition to my home.",
    "The product is a bit of a letdown. I expected more for the price.",
    "I'm very happy with my purchase. It's been a great value.",
    "The product is a bit of a novelty, but it's a fun one.",
    "I'm very impressed with the performance of this product.",
    "The product is a bit of a disappointment. I wouldn't buy it again.",
    "I'm very satisfied with this product. It's been a great experience.",
    "The product is a bit of a letdown. I expected better quality.",
    "I'm very happy with my purchase. It's been a great product.",
    "The product is a bit of a novelty, but it's a cool one.",
    "I'm very impressed with the design of this product.",
    "The product is a bit of a disappointment. I wouldn't recommend it to others.",
    "I'm very satisfied with this product. It's been a great tool.",
    "The product is a bit of a letdown. I expected more from the description.",
    "I'm very happy with my purchase. It's been a great addition to my collection.",
    "The product is a bit of a novelty, but it's a unique one."
]

def createReviews(minReviews, maxReviews):
    numReviews = random.randint(minReviews, maxReviews)
    reviews = []
    for _ in range(numReviews):
        year = random.randint(2018, 2025)
        month = random.randint(1, 12)
        day = random.randint(1, 28) # To avoid month length issues
        reviews.append({
            "userDisplayName": random.choice(userNames),
            "rating": random.randint(1, 5),
            "comment": random.choice(comments),
            "date": datetime(year, month, day)
        })
    return reviews



result = productsCollection.insert_many(products)
print(f"✓ {len(result.inserted_ids)} unique products added successfully")

closeConnection(mongoClient)
